#! /bin/bash

FILE=`%%%{PBXUtilityScriptsPath}%%%/AskUserForNewFileDialog "Save As" ".gitignore"`
echo $FILE
touch $FILE

FILEX=`%%%{PBXUtilityScriptsPath}%%%/AskUserForNewFileDialog "Save As" ".gitattributes"`
echo $FILEX
touch $FILEX

# This script creates the .gitignore and .gitattributes in the current folder.

echo "# finder
.DS_Store

# xcode per-user config
*.mode1
*.mode1v3
*.mode2v3
*.perspective
*.perspectivev3
*.pbxuser

# build products
build/
*.[oa]

# automatic backup files
*~.nib
*.swp
*~

echo "*.pbxproj -crlf -diff -merge" >> $FILEX